// Run: node --experimental-strip-types lib/session.test.mjs  (or npx tsx)
import assert from "node:assert/strict";
import { apply } from "./session.ts";
const base = () => ({ code: "ABCD", mode: "timer", task: "", status: "idle", startedAt: null, endsAt: null, breaksLeft: 2, breakUntil: null, resumeEndsAt: null, submitted: false, away: false, strikes: 0, log: [], updatedAt: 0 });
let s = apply(base(), { type: "start", mode: "timer", minutes: 25 });
assert.equal(s.status, "locked");
s = apply(s, { type: "break" });
assert.equal(s.status, "break"); assert.equal(s.breaksLeft, 1);
s = apply(s, { type: "endBreak" });
assert.equal(s.status, "locked");
s = apply(s, { type: "submit" });
assert.equal(s.status, "locked", "timer mode: submit does not unlock");
s = apply(base(), { type: "start", mode: "assignment" });
assert.equal(s.endsAt, null);
s = apply(s, { type: "submit" });
assert.equal(s.status, "unlocked");
// watch mode: leaving without a break = strike + 5 min; on break it's fine; back clears
s = apply(base(), { type: "start", mode: "watch", minutes: 50, task: "essay" });
const end0 = s.endsAt;
s = apply(s, { type: "away" });
assert.equal(s.strikes, 1); assert.equal(s.away, true); assert.equal(s.endsAt, end0 + 5 * 60000);
s = apply(s, { type: "away" });
assert.equal(s.strikes, 1, "away is idempotent while still away");
s = apply(s, { type: "back" });
assert.equal(s.away, false);
s = apply(s, { type: "break" });
s = apply(s, { type: "away" });
assert.equal(s.strikes, 1, "no strike during a break");
s = apply(base(), { type: "start", mode: "timer", minutes: 25 });
s = apply(s, { type: "away" });
assert.equal(s.strikes, 0, "no strikes outside watch mode");
console.log("ok");
